### ISSUE TITLE
When you open app screen it’s blank

### ISSUE THREAD

**Issue by johnj246810** [DiscipleTools/disciple-tools-mobile-app#129]
**Describe the bug**
When you open the app contacts are not listed. You have to search for a contact by typing their info in to find them. 

 **To Reproduce**
1. Open app
2. Blank screen
3. No contacts listed 

 **Expected behavior**
Screen shows all contacts (like on website)

 **Smartphone (please complete the following information):**
 - Device: iPhone 6S and Android
 - OS: Latest
 - App Version Expo

 **Additional context**
Add any other context about the problem here

**Comment by zdmc23** [comment]
@johnj246810 Please try to uninstall Expo, and reinstall, and then reload the App.  This was a known issue that should have been fixed with a more recent release, but you may have older release cached

**Comment by zdmc23** [comment]
If that doesn't work, then confirm that you have Contacts assigned to your Multiplier Role

**Comment by mikeallbutt** [comment]
I am still getting this bug, even when signed in as other roles. It will confuse users for sure

**Comment by zdmc23** [comment]
@mikeallbutt should this be resolved by #50 ?

+ @johnj246810

**Comment by mikeallbutt** [comment]
> @mikeallbutt should this be resolved by #50 ?
> 
> * @johnj246810

Issue #50 will not really help this issue. There are contacts that should be displaying immediately. Telling the user to refresh the screen will be a short term fix, so they will get their list, but the list should be there first time.

**Comment by zdmc23** [comment]
The workaround that I often need to use to resolve this is to run it locally at least once after reinstall of Expo, and then subsequent Expo loads work as expected.  I suspect that it had to do with async storage

**Comment by mikeallbutt** [comment]
@zdmc23 should this issue be closed since it won't be fixed?

**Comment by zdmc23** [comment]
Resolved as of v1.10
