### ISSUE TITLE
Android clock & phone icons are missing

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#660]
The top row of the operating system is just a white strip and the clock or other phone icons are not displayed.

What should be displayed 
![IMG_20220619_143604.jpg](https://user-images.githubusercontent.com/43966676/174497544-4ca5b9df-6e6d-464d-8df6-66313556f001.jpg)

DT app
![IMG_20220619_143345.jpg](https://user-images.githubusercontent.com/43966676/174497566-42950b59-c84f-4752-bd8c-acfd6792f9f0.jpg)

**Comment by jhenterprise** [comment]
I guess it is already fixed.  The clock is already displayed.
![WhatsApp Image 2022-07-01 at 3 41 44 PM](https://user-images.githubusercontent.com/9843021/176880244-bcbd3140-4ca8-4c98-9f56-9876840c09b8.jpeg)

**Comment by mikeallbutt** [comment]
I am pretty sure it is not fixed. When using the app via Expo all is fine, but the app in the store has this issue.
